version: '3'
services: 
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes: 
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: suite340
      MYSQL_DATABASE: uptask_db
    ports: 
      - 3306:3306
    networks:
      - net
  
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:5
    restart: always
    ports:
      -  8081:80
    environment:
      PMA_HOST: db
    networks:
      - net
networks: 
  net: